/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mamapp;

import java.awt.FlowLayout;
import java.util.TimerTask;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author ztjam
 */
public class MAMGUI extends javax.swing.JFrame {

    /**
     * Creates new form MAMGUI
     */
    public MAMGUI() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WaterGRP = new javax.swing.ButtonGroup();
        ReminderGRP = new javax.swing.ButtonGroup();
        StretchGRP = new javax.swing.ButtonGroup();
        BreakGRP = new javax.swing.ButtonGroup();
        TitleLBL = new javax.swing.JLabel();
        WaterLBL = new javax.swing.JLabel();
        StretchLBL = new javax.swing.JLabel();
        BreakLBL = new javax.swing.JLabel();
        ConfirmBTN = new javax.swing.JButton();
        WaterTF = new javax.swing.JTextField();
        StretchTF = new javax.swing.JTextField();
        BreakTF = new javax.swing.JTextField();
        InfoLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLBL.setText("MAM");

        WaterLBL.setText("Water Reminder");

        StretchLBL.setText("Stretch Reminder");

        BreakLBL.setText("Break reminder");

        ConfirmBTN.setText("Confirm");
        ConfirmBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmBTNActionPerformed(evt);
            }
        });

        InfoLBL.setText("Please enter how many minutes from now you would like a reminder.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(309, 309, 309)
                .addComponent(ConfirmBTN)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(TitleLBL)
                        .addGap(332, 332, 332))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InfoLBL)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(WaterLBL)
                                    .addComponent(StretchLBL)
                                    .addComponent(BreakLBL))
                                .addGap(136, 136, 136)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(WaterTF, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(StretchTF)
                                    .addComponent(BreakTF))))
                        .addGap(159, 159, 159))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(TitleLBL)
                .addGap(18, 18, 18)
                .addComponent(InfoLBL)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WaterLBL)
                    .addComponent(WaterTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StretchLBL)
                    .addComponent(StretchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BreakLBL)
                    .addComponent(BreakTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(ConfirmBTN)
                .addGap(73, 73, 73))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmBTNActionPerformed
        timer2 t = new timer2();
        timer m = new timer();
        timer3 q = new timer3();
        
        try{
       m.setBreakNo(Integer.parseInt(BreakTF.getText()));
       m.setStretchNo(Integer.parseInt(StretchTF.getText()));
       m.setWaterNo(Integer.parseInt(WaterTF.getText()));
       t.setBreakNo(Integer.parseInt(BreakTF.getText()));
       t.setStretchNo(Integer.parseInt(StretchTF.getText()));
       t.setWaterNo(Integer.parseInt(WaterTF.getText()));
       q.setBreakNo(Integer.parseInt(BreakTF.getText()));
       q.setStretchNo(Integer.parseInt(StretchTF.getText()));
       q.setWaterNo(Integer.parseInt(WaterTF.getText()));
       
       JOptionPane.showMessageDialog(null,"Minutes before water Break: " + m.WaterNo + "\n" + "Minutes before Stretch Break: " + m.StretchNo + "\n" + "Minutes before main Break: " + m.BreakNo );
        }
        catch (Exception e){
                JOptionPane.showMessageDialog(null,"Please enter a valid integer.");
                }
        
       
       m.newWaterNo = m.WaterNo*60; 
       t.newBreakNo = t.BreakNo*60;
       q.newStretchNo = q.StretchNo*60;
       
       t.timer2.scheduleAtFixedRate(t.task2,1000,1000);
      m.timer.scheduleAtFixedRate(m.task,1000,1000);
      q.timer3.scheduleAtFixedRate(q.task3,1000,1000);
      
      
       
       
    }//GEN-LAST:event_ConfirmBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MAMGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MAMGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MAMGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MAMGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MAMGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BreakGRP;
    private javax.swing.JLabel BreakLBL;
    private javax.swing.JTextField BreakTF;
    private javax.swing.JButton ConfirmBTN;
    private javax.swing.JLabel InfoLBL;
    private javax.swing.ButtonGroup ReminderGRP;
    private javax.swing.ButtonGroup StretchGRP;
    private javax.swing.JLabel StretchLBL;
    private javax.swing.JTextField StretchTF;
    private javax.swing.JLabel TitleLBL;
    private javax.swing.ButtonGroup WaterGRP;
    private javax.swing.JLabel WaterLBL;
    private javax.swing.JTextField WaterTF;
    // End of variables declaration//GEN-END:variables
}
